name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # This will trigger the workflow when a tag starting with 'v' (e.g., v1.0.0) is pushed.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry  # Install poetry for dependency management.
          poetry install  # Install project dependencies.
          poetry build
          pip install dist/*.whl

      # Ensure versioning is updated via git tag
      - name: Update version from tag
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
          poetry version $TAG_VERSION

      # Commit the changes to pyproject.toml
      - name: Commit version update and update README
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          python tools/update_readme.py
          git add pyproject.toml README.md
          git commit -m "Bump version in pyproject.toml to ${TAG_VERSION}"
        env:
          TAG_VERSION: ${{ env.TAG_VERSION }}

      # Push the changes to GitHub
      - name: Push changes to GitHub
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main  # Push to the main branch

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine  # Install twine for uploading to PyPI.
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
